server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          # путь к папке, где файлы настроек
          search-locations: file:./central-configs/
  profiles:
    active: native # локальная файловая система вместо Git

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Адрес сервера Eureka


#    spring:
#      application:
#        name: config-server
#      cloud:
#        config:
#          server:
#            git:
#              uri: https://github.com/DedovaA/central-config.git
#              default-label: main
#              username: login
#              password: token
#              clone-on-start: true