# Общие настройки для ВСЕХ сервисов
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Адрес сервера Eureka
  instance:
    prefer-ip-address: true # Чтобы в Eureka отображались IP-адреса, а не случайные ID контейнеров
